### ISSUE TITLE
Exiting -- Must provide one file

### ISSUE THREAD

**Issue by Bidulle59** [frank038/gtk3vlcplayer#1]
Hi,
I just try your code on a fresh raspberry Pi400.
I download your Git with Visual Stidio Code.
When I run it, I have an error with a pop-up: "Existing -- Must provide one file"

Try to put the http exemple you provide, or the same file in local path on the line 45 (MRL) but I have the same error.

**Comment by frank038** [comment]
That message appears when no file has been passed as first argument.
The command is: ./gtk3vlcplayer.py media_file OR python3 gtk3vlcplayer.py media_file
I cannot reproduce this issue.

**Comment by frank038** [comment]
Not a bug.
